# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistics.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10statistics.proto\x12\x05stats\"&\n\x06Sensor\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61taTipe\x18\x02 \x01(\t\"+\n\x0bMeanRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61taTipe\x18\x02 \x01(\t\"\x1e\n\rStringMessage\x12\r\n\x05value\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2n\n\nStatistics\x12+\n\ngetSensors\x12\x0c.stats.Empty\x1a\r.stats.Sensor0\x01\x12\x33\n\x07getMean\x12\x12.stats.MeanRequest\x1a\x14.stats.StringMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statistics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSOR']._serialized_start=27
  _globals['_SENSOR']._serialized_end=65
  _globals['_MEANREQUEST']._serialized_start=67
  _globals['_MEANREQUEST']._serialized_end=110
  _globals['_STRINGMESSAGE']._serialized_start=112
  _globals['_STRINGMESSAGE']._serialized_end=142
  _globals['_EMPTY']._serialized_start=144
  _globals['_EMPTY']._serialized_end=151
  _globals['_STATISTICS']._serialized_start=153
  _globals['_STATISTICS']._serialized_end=263
# @@protoc_insertion_point(module_scope)
