# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import magazzino_pb2 as magazzino__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in magazzino_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class MagazzinoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Preleva = channel.unary_unary(
                '/magazzino.Magazzino/Preleva',
                request_serializer=magazzino__pb2.StringMessage.SerializeToString,
                response_deserializer=magazzino__pb2.Prodotto.FromString,
                _registered_method=True)
        self.Deposita = channel.unary_unary(
                '/magazzino.Magazzino/Deposita',
                request_serializer=magazzino__pb2.Prodotto.SerializeToString,
                response_deserializer=magazzino__pb2.StringMessage.FromString,
                _registered_method=True)
        self.Svuota = channel.unary_unary(
                '/magazzino.Magazzino/Svuota',
                request_serializer=magazzino__pb2.StringMessage.SerializeToString,
                response_deserializer=magazzino__pb2.StringMessage.FromString,
                _registered_method=True)


class MagazzinoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Preleva(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deposita(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Svuota(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MagazzinoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Preleva': grpc.unary_unary_rpc_method_handler(
                    servicer.Preleva,
                    request_deserializer=magazzino__pb2.StringMessage.FromString,
                    response_serializer=magazzino__pb2.Prodotto.SerializeToString,
            ),
            'Deposita': grpc.unary_unary_rpc_method_handler(
                    servicer.Deposita,
                    request_deserializer=magazzino__pb2.Prodotto.FromString,
                    response_serializer=magazzino__pb2.StringMessage.SerializeToString,
            ),
            'Svuota': grpc.unary_unary_rpc_method_handler(
                    servicer.Svuota,
                    request_deserializer=magazzino__pb2.StringMessage.FromString,
                    response_serializer=magazzino__pb2.StringMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'magazzino.Magazzino', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Magazzino(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Preleva(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/magazzino.Magazzino/Preleva',
            magazzino__pb2.StringMessage.SerializeToString,
            magazzino__pb2.Prodotto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deposita(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/magazzino.Magazzino/Deposita',
            magazzino__pb2.Prodotto.SerializeToString,
            magazzino__pb2.StringMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Svuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/magazzino.Magazzino/Svuota',
            magazzino__pb2.StringMessage.SerializeToString,
            magazzino__pb2.StringMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
