# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: magazzino.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmagazzino.proto\x12\tmagazzino\" \n\rStringMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\",\n\x08Prodotto\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0ctipoProdotto\x18\x02 \x01(\t2\xc4\x01\n\tMagazzino\x12:\n\x07Preleva\x12\x18.magazzino.StringMessage\x1a\x13.magazzino.Prodotto\"\x00\x12;\n\x08\x44\x65posita\x12\x13.magazzino.Prodotto\x1a\x18.magazzino.StringMessage\"\x00\x12>\n\x06Svuota\x12\x18.magazzino.StringMessage\x1a\x18.magazzino.StringMessage\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'magazzino_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STRINGMESSAGE']._serialized_start=30
  _globals['_STRINGMESSAGE']._serialized_end=62
  _globals['_PRODOTTO']._serialized_start=64
  _globals['_PRODOTTO']._serialized_end=108
  _globals['_MAGAZZINO']._serialized_start=111
  _globals['_MAGAZZINO']._serialized_end=307
# @@protoc_insertion_point(module_scope)
